# SmartWebBot v2.0 Configuration
# Advanced Intelligent Web Automation System

# Browser Configuration
browser:
  default_browser: "chrome"  # chrome, firefox, edge
  headless: false
  window_size: [1920, 1080]
  implicit_wait: 10
  page_load_timeout: 30
  download_directory: "downloads"
  user_agent: null  # Use default or specify custom
  proxy: null  # Proxy server URL
  extensions: []  # List of extension paths
  save_session: true

# Automation Behavior
automation:
  screenshot_on_error: true
  retry_attempts: 3
  delay_between_actions: 1.0
  save_session: true
  element_timeout: 10
  smart_wait: true
  anti_detection: true
  human_like_delays: true

# AI and Intelligence Settings
ai:
  enabled: true
  provider: "ollama"  # ollama, openai, groq
  model: "gemma3:4b"  # Model name for the selected provider
  element_detection_model: "advanced"
  decision_making_level: "adaptive"
  learning_enabled: true
  confidence_threshold: 0.8
  fallback_strategies: true

# Security Configuration
security:
  encryption_enabled: true
  credential_storage: "encrypted_file"
  session_encryption: true
  secure_headers: true
  certificate_verification: true

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_logging: true
  console_logging: true
  json_logging: true
  performance_logging: true
  log_directory: "logs"
  max_file_size: 10485760  # 10MB in bytes
  backup_count: 5

# Data Handling
data:
  export_format: "csv"  # csv, json, xlsx
  output_directory: "output"
  compression_enabled: true
  data_validation: true
  schema_enforcement: true

# Performance Settings
performance:
  enable_monitoring: true
  metrics_collection: true
  optimization_level: "balanced"  # fast, balanced, thorough
  memory_limit_mb: 1024
  
# Plugin System
plugins:
  enabled: true
  auto_load: true
  plugin_directory: "plugins"
  
# Advanced Features
advanced:
  parallel_processing: false
  batch_operations: true
  smart_caching: true
  predictive_loading: true